#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Android-Gradle.yml
name: Build

env:
  Branch: ${{github.ref_name}}
  GH_TOKEN: ${{ github.token }}
  Artifacts: app/build/outputs/apk/debug/app-debug.apk
  WorkingDirectory: #/Android

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo and submodules
      run: git clone --recurse-submodules https://github.com/${{github.repository}}.git . --branch ${{env.Branch}}

    - name: Get current date, commit hash and count
      run: |
        echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: .${{env.WorkingDirectory}}
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: .${{env.WorkingDirectory}}
      run: ./gradlew build --warning-mode all

    - name: List files
      working-directory: .${{env.WorkingDirectory}}
      run: ls -R

    - name: Compress artifacts
      run: |
        mkdir Release
        7z a "Release/${{env.Title}}.zip" "${{github.workspace}}/${{env.Artifacts}}/*" -mx=9
        cp "Release/${{env.Title}}.zip" "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Purge tag - latest-${{env.Branch}}
      run: |
        gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true

    - name: Release - archive-${{env.Branch}}
      run: |
        gh release create archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest
        Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" || true
        gh release upload archive-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Release - latest-${{env.Branch}}
      run: |
        gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=true --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive
        Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}.zip"
