#Template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Android-Gradle.yml
name: Build

env:
  Branch: ${{github.ref_name}}
  GH_TOKEN: ${{ github.token }}
  Artifacts: app/build/outputs/apk/debug/app-debug.apk
  WorkingDirectory: #/Android

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo and submodules
      run: git clone --recurse-submodules https://github.com/${{github.repository}}.git . --branch ${{env.Branch}}

    - name: Get current date, commit hash and count
      run: |
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
        echo "CommitCount=$(git rev-list --count ${{env.Branch}} --)" >> $GITHUB_ENV
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: .${{env.WorkingDirectory}}
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: .${{env.WorkingDirectory}}
      run: ./gradlew build --warning-mode all

    - name: List files
      working-directory: .${{env.WorkingDirectory}}
      run: ls -R

    - name: Upload Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: "${{github.event.repository.name}}_r${{env.CommitCount}}@${{env.CommitHashShort}}"
        path: "${{github.workspace}}${{env.WorkingDirectory}}/${{env.Artifacts}}/"

    - name: Release
      working-directory: .${{env.WorkingDirectory}}
      run: |
        gh release create r${{env.CommitCount}} --generate-notes --latest=false --prerelease --title "[${{env.CommitDate}}] ${{github.event.repository.name}} r${{env.CommitCount}}@${{env.CommitHashShort}}"
        gh release upload r${{env.CommitCount}} "${{env.Artifacts}}"
