#Template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-MSBuild.yml
name: Build

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Platform: #Any CPU|Win32|x86|x64 - Check .sln file for available ones
  Configuration: Release
  Artifacts: build/Release
  Title: ${{github.event.repository.name}}
  Solution: ${{github.event.repository.name}}.sln # .
  Executable: ${{github.event.repository.name}}.exe # *
#  DXSDK_DIR: C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\
#  VULKAN_VERSION: 1.1.130.0

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-2022
    steps:

    - name: Clone repo and submodules
      run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --depth 1 --recurse-submodules

    - name: Get current date, commit hash and count
      run: |
        echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

#    - name: Install Windows 8.1 SDK
#      shell: powershell
#      run: |
#        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
#        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"

#    - name: Install .NET Framework 4.6.1 Developer Pack
#      shell: powershell
#      run: |
#        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/?linkid=2099470 -OutFile ndp461-devpack-kb3105179-enu.exe -UseBasicParsing
#        Start-Process -Wait ./ndp461-devpack-kb3105179-enu.exe -ArgumentList "/Quiet"

#    - name: Cache DirectX SDK
#      id: DXSDK_Jun10
#      uses: actions/cache@v4
#      with:
#        path: ${{env.DXSDK_DIR}}
#        key: DXSDK_Jun10
#    - name: Install DirectX SDK
#      if: steps.DXSDK_Jun10.outputs.cache-hit != 'true'
#      shell: powershell
#      run: |
#        Invoke-WebRequest -Method Get -Uri https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -OutFile DXSDK_Jun10.exe -UseBasicParsing
#        Start-Process -Wait ./DXSDK_Jun10.exe -ArgumentList "/U"
#    - name: Set DXSDK_DIR
#      run: echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\" >> $env:GITHUB_ENV
# NOTE: STORING CACHE REQUIRES THE RUN TO SUCCEED, SO IF IT'S FAILING, TRY TEMPORARILY REMOVING ALL THE STEPS BELOW THIS LINE

#    - name: Cache Vulkan SDK
#      id: cache-vulkan-sdk
#      uses: actions/cache@v5
#      with:
#        path: "C:\\VulkanSDK\\${{env.VULKAN_VERSION}}"
#        key: VulkanSDK
#    - name: Install Vulkan SDK
#      if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
#      shell: powershell
#      run: |
#        echo "VULKAN_SDK=C:\VulkanSDK\${{env.VULKAN_VERSION}}" >> $env:GITHUB_ENV
#        Invoke-WebRequest -Method Get -Uri https://web.archive.org/web/20200413110014if_/https://sdk.lunarg.com/sdk/download/${{env.VULKAN_VERSION}}/windows/VulkanSDK-${{env.VULKAN_VERSION}}-Installer.exe -OutFile VulkanSDK.exe -UseBasicParsing
#        Start-Process -Wait ./VulkanSDK.exe -ArgumentList "/S", "--accept-licenses", "--default-answer", "--confirm-command install", "com.lunarg.vulkan.sdl2", "com.lunarg.vulkan.glm"
# NOTE: STORING CACHE REQUIRES THE RUN TO SUCCEED, SO IF IT'S FAILING, TRY TEMPORARILY REMOVING ALL THE STEPS BELOW THIS LINE

#    - name: Install TortoiseSVN
#      run: |
#        curl -L https://cfhcable.dl.sourceforge.net/project/tortoisesvn/1.14.9/Application/TortoiseSVN-1.14.9.29743-x64-svn-1.14.5.msi?viasf=1 -o "TortoiseSVN.msi"
#        Start-Process -Wait "msiexec" -ArgumentList "/package", "TortoiseSVN.msi", "/quiet"

#    - name: Install Qt
#      uses: jurplel/install-qt-action@v4
#      with:
#        version: '6.6.0'
#        host: 'windows'
#        target: 'desktop'
#        arch: 'win64_msvc2019_64'
#        modules: 'addons.qtmultimedia'

#    - name: Install Python 2.6
#      shell: powershell
#      run: |
#        Invoke-WebRequest -Method Get -Uri https://www.python.org/ftp/python/2.6.6/python-2.6.6.msi -OutFile python.msi -UseBasicParsing
#        Start-Process -Wait ./python.msi -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1"
#        python --version
#        $Env:Path = "C:\Python26;" + $Env:Path
#        python --version
# NOTE: ADD THE LAST 3 LINES ABOVE RIGHT BEFORE MSBUILD IN THE BUILD STEP TO SWITCH AND CHECK PYTHON VERSION

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore "${{env.Solution}}"

    - name: Build
      run: msbuild /m "${{env.Solution}}" /p:Configuration="${{env.Configuration}}" /p:PlatformToolset=v143 #/p:Platform="${{env.Platform}}" /p:IncludePath="C:\Path\to\Include" /p:LibPath="C:\Path\to\Lib" /p:AdditionalIncludePaths="C:\Path\to\external\include" /p:AdditionalLibraryDirectories="C:\Path\to\external\lib" /p:AdditionalDependencies=file.lib /p:LanguageStandard="stdcpp17"

#    - name: Meson Build
#      uses: BSFishy/meson-build@v1.0.3
#      with:
#        action: build

    - name: List files
      run: ls -R

#    - name: Deploy - Qt
#      run: |
#        windeployqt.exe "${{github.workspace}}/${{env.Artifacts}}/${{env.Executable}}"

#      - name: Deploy - vcpkg
#        shell: cmd
#        run: |
#          If exist "vcpkg_installed\${{env.Platform}}-windows\bin\*.dll" (copy "vcpkg_installed\${{env.Platform}}-windows\bin\*.dll" "${{env.Artifacts}}")
#          If exist "vcpkg\installed\${{env.Platform}}-windows\bin\*.dll" (copy "vcpkg\installed\${{env.Platform}}-windows\bin\*.dll" "${{env.Artifacts}}")

    - name: Upload Installer Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: "${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}"
        path: "${{github.workspace}}/${{env.Artifacts}}/"

    - name: Compress artifacts
      run: |
        mkdir Release
        7z a "Release/${{env.Title}}.zip" "${{github.workspace}}/${{env.Artifacts}}/*" -mx=9
        cp "Release/${{env.Title}}.zip" "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Purge tag - latest-${{env.Branch}}
      run: |
        gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true

    - name: Release - archive
      run: |
        gh release create archive --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest
        Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" || true
        gh release upload archive --repo ${{github.repository}} --clobber "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Release - latest-${{env.Branch}}
      run: |
        gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=true --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive
        Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}.zip"

#Errors and solutions:

# error MSB3644: The reference assemblies for .NETFramework,Version=vX.Y.Z were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. 
# Uncomment the "- name: Install .NET Framework 4.6.1 Developer Pack" section and update the version and URL with X.Y (or X.Y.Z) from https://dotnet.microsoft.com/en-us/download/visual-studio-sdks?cid=msbuild-developerpacks

# error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".  
# Specify PlatformToolset in the msbuild step, e.g.: /p:PlatformToolset=v143 for windows-2022

# LINK : fatal error LNK1181: cannot open input file 'dependency32.lib' [C:\a\Project\Project.vcxproj]
# Install the missing packages via vcpkg before the building step. Example:
#    - name: Install vcpkg
#      uses: lukka/run-vcpkg@v11
#      with:
#        vcpkgGitCommitId: 654410ee8e11f0610c11a4a49a8827a84be5e187
#    - name: Install dependencies
#      run: |
#        vcpkg install dependency

# error MSB8036: The Windows SDK version 10.0.#####.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". 
# Add/uncomment the SDK installer step above and replace the 8.1 installer download link with #####'s from here: https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/index-legacy

# Error: 403 "Resource not accessible by integration"
# Usually means it can't create a release if a new workflow is still running. Otherwise, set Workflow permissions to Read and write permissions in the repo's Settings > Actions > General
